#  docker-compose -f .\compose_gogol.yml up -d --build

version: '3.8'

services:

  backend:
    build: ./backend
    container_name: gogol_backend
#    command: uvicorn main:app --host 0.0.0.0 --port 8002
    command: gunicorn -b 0.0.0.0:8002 -k uvicorn.workers.UvicornWorker main:app
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
    #      - .:/app
    ports:
      - "8002:8002"
    env_file:
      - ./backend/.env_gogol

  frontend:
    build:
      context: ./frontend
      dockerfile: ./gogol.Dockerfile
    container_name: gogol_frontend
    volumes:
      - ./frontend/nginx/gogol/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/nginx/gogol/configs:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
      - "82:82"
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw