#  docker-compose -f compose_dev.yml up -d --build

version: '3.8'

services:

  backend_gogol:
    build: ./backend
    volumes:
      - ./backend:/app
    command: gunicorn -b 0.0.0.0:8002 -k uvicorn.workers.UvicornWorker main:app
    ports:
      - "8002:8002"
    env_file:
      - ./backend/.env_gogol
    restart: always

  frontend_gogol:
    build:
      context: ./frontend
      dockerfile: ./gogol.Dockerfile
    volumes:
      - ./frontend/nginx_dev/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/nginx_dev/gogol/configs:/etc/nginx/conf.d:ro
    ports:
      - "81:81"
      - "82:82"
    restart: always

  nginx:
    image: nginx:1.22.1
    volumes:
      - ./nginx_main/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_main/dev:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
